import { StyleSheet, Platform, StatusBar } from 'react-native';
import COLORS from '../constants/colors';

// =============================================
// STYLESHEET
// =============================================
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgDark },
  screenContainer: { flex: 1 },
  card: { backgroundColor: COLORS.bgCard, borderRadius: 16, borderWidth: 1, borderColor: COLORS.border, padding: 20 },
  actionButton: { borderRadius: 14, paddingVertical: 16, paddingHorizontal: 24, alignItems: 'center', justifyContent: 'center' },
  actionButtonContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  actionButtonText: { fontSize: 16, fontWeight: '600' },
  waveformContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, height: 70 },
  waveformBar: { width: 6, borderRadius: 3 },
  waveformPreview: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, height: 70, marginTop: 32 },
  splashContainer: { flex: 1, backgroundColor: COLORS.bgDark, justifyContent: 'center', alignItems: 'center' },
  splashLogo: { width: 100, height: 100, borderRadius: 28, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
  splashLogoText: { fontSize: 48, fontWeight: 'bold', color: '#FFF' },
  splashTitle: { fontSize: 42, fontWeight: 'bold', color: COLORS.textPrimary, letterSpacing: 6 },
  splashTagline: { fontSize: 14, color: COLORS.textSecondary, marginTop: 12, letterSpacing: 1 },
  loginContainer: { flex: 1, backgroundColor: COLORS.bgDark },
  loginSafeArea: { flex: 1, justifyContent: 'center', paddingHorizontal: 24 },
  loginHeader: { alignItems: 'center', marginBottom: 32 },
  loginLogo: { width: 70, height: 70, borderRadius: 20, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  loginLogoText: { fontSize: 32, fontWeight: 'bold', color: '#FFF' },
  loginTitle: { fontSize: 28, fontWeight: 'bold', color: COLORS.textPrimary, marginBottom: 8 },
  loginSubtitle: { fontSize: 16, color: COLORS.textSecondary },
  loginCard: { marginBottom: 24 },
  inputGroup: { marginBottom: 20 },
  inputLabel: { fontSize: 14, fontWeight: '600', color: COLORS.textPrimary, marginBottom: 8 },
  textInput: { backgroundColor: COLORS.bgInput, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, color: COLORS.textPrimary },
  signupRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  signupText: { fontSize: 15, color: COLORS.textSecondary },
  signupLink: { fontSize: 15, fontWeight: '600', color: COLORS.accent },
  topBarWrapper: { backgroundColor: COLORS.bgDark, borderBottomWidth: 1, borderBottomColor: COLORS.border, paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 },
  topBar: { height: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16 },
  topBarIcon: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
  topBarIconPlaceholder: { width: 44 },
  topBarTitle: { fontSize: 18, fontWeight: '700', color: COLORS.textPrimary, letterSpacing: 0.5 },
  topBarAvatar: { width: 36, height: 36, borderRadius: 12, backgroundColor: COLORS.bgElevated, justifyContent: 'center', alignItems: 'center' },
  tabBarWrapper: { backgroundColor: COLORS.bgCard, borderTopWidth: 1, borderTopColor: COLORS.border },
  tabBar: {  height: 80, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingBottom: 25, paddingTop: 20 },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 8 },
  tabIconWrapper: { width: 44, height: 36, justifyContent: 'center', alignItems: 'center', borderRadius: 10 },
  tabIconActive: { backgroundColor: 'rgba(99, 102, 241, 0.15)' },
  tabLabel: { fontSize: 11, fontWeight: '500', marginTop: 4 },
  homeContainer: { flex: 1 },
  homeContent: { padding: 20, paddingBottom: 32 },
  homeWelcome: { fontSize: 28, fontWeight: 'bold', color: COLORS.textPrimary, marginBottom: 8 },
  homeSubtitle: { fontSize: 15, color: COLORS.textSecondary, lineHeight: 22, marginBottom: 28 },
  featureGrid: { flexDirection: 'row', gap: 14, marginBottom: 28 },
  featureCard: { flex: 1, borderRadius: 20, padding: 20, aspectRatio: 1, justifyContent: 'center', alignItems: 'center' },
  featureIconBg: { width: 56, height: 56, borderRadius: 16, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', marginBottom: 14 },
  featureTitle: { fontSize: 15, fontWeight: '700', color: '#FFF', marginBottom: 4 },
  featureSubtitle: { fontSize: 12, color: 'rgba(255,255,255,0.75)' },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: COLORS.textPrimary, marginBottom: 16 },
  quickActionCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.bgCard, borderRadius: 16, borderWidth: 1, borderColor: COLORS.border, padding: 16, marginBottom: 12 },
  quickActionIcon: { width: 48, height: 48, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  quickActionText: { flex: 1, marginLeft: 14 },
  quickActionTitle: { fontSize: 15, fontWeight: '600', color: COLORS.textPrimary, marginBottom: 2 },
  quickActionSubtitle: { fontSize: 13, color: COLORS.textMuted },
  historyContainer: { flex: 1, padding: 20 },
  historyCard: { marginBottom: 14 },
  historyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  historyTag: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  historyTagText: { fontSize: 12, fontWeight: '600', color: '#FFF' },
  historyTime: { fontSize: 12, color: COLORS.textMuted },
  historyText: { fontSize: 15, color: COLORS.textPrimary, lineHeight: 22, marginBottom: 14 },
  speechScreen: { flex: 1, padding: 24, justifyContent: 'space-between' },
  speechContent: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  speechInstruction: { fontSize: 18, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 26 },
  speechStatusText: { fontSize: 18, color: COLORS.textPrimary, marginBottom: 16 },
  recIndicator: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(239, 68, 68, 0.15)', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20 },
  recDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: COLORS.error, marginRight: 8 },
  recText: { fontSize: 14, fontWeight: '700', color: COLORS.error },
  speechActions: { paddingTop: 20 },
  speechSubtext: { fontSize: 15, color: COLORS.textSecondary, marginBottom: 20 },
  convertedTextCard: { width: '100%', marginBottom: 32 },
  convertedText: { fontSize: 20, fontWeight: '600', color: COLORS.textPrimary, textAlign: 'center' },
  avatarCircle: { width: 140, height: 140, borderRadius: 70, backgroundColor: COLORS.bgElevated, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
  completeText: { fontSize: 16, color: COLORS.emerald, fontWeight: '600' },
  actionBar: { flexDirection: 'row', justifyContent: 'space-around', paddingTop: 20, borderTopWidth: 1, borderTopColor: COLORS.border },
  actionBarItem: { alignItems: 'center', padding: 12 },
  actionBarLabel: { fontSize: 12, color: COLORS.textSecondary, marginTop: 6, fontWeight: '500' },
  signScreen: { flex: 1, padding: 24 },
  settingsContainer: { flex: 1 },
  settingsHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  backBtn: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center', marginRight: 8 },
  settingsHeaderTitle: { fontSize: 18, fontWeight: '700', color: COLORS.textPrimary },
  settingsTitleSection: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 8 },
  settingsTitle: { fontSize: 26, fontWeight: 'bold', color: COLORS.textPrimary, marginBottom: 6 },
  settingsSubtitle: { fontSize: 15, color: COLORS.textSecondary },
  settingsList: { paddingHorizontal: 20, paddingTop: 16, gap: 12 },
  settingsItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: COLORS.bgCard, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, padding: 14 },
  settingsItemLeft: { flexDirection: 'row', alignItems: 'center' },
  settingsIcon: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  settingsItemText: { fontSize: 15, fontWeight: '500', color: COLORS.textPrimary },
  profileCard: { margin: 20 },
  readOnlyInput: { opacity: 0.6, justifyContent: 'center' },
  readOnlyText: { fontSize: 16, color: COLORS.textSecondary },
  logoutSection: { paddingHorizontal: 20, paddingTop: 32, paddingBottom: 40 },
});

export default styles;
